[package]
name = "kyle/game-inc"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
binder = "hahafunnyman/binder@0.2.0"
replica = "ivasmigins/replica@0.1.0"
fusion = "realdeedy/fusion@0.3.0"

[server-dependencies]
profileservice = "firebird702/profileservice@1.1.0"